### play sound test
GET http://localhost:80/api/clear-devices

### play sound test
GET http://localhost:80/api/playsoundtest

### start color animation for all controllers
GET http://localhost:80/api/setColorAnimation

### test color animation without loop
GET http://localhost:80/api/setRedAnimationTest

### clear all devices
GET http://localhost:80/api/clear-devices

### test rumble
GET http://localhost:80/api/rumble/255

### test set Color
GET http://localhost:80/api/setColor/pastel_green

### test set Color
GET http://localhost:80/api/setColor/light_blue

### test set Color
GET http://localhost:80/api/setColor/aqua

### test set Color
GET http://localhost:80/api/setColor/green

### test set Color
GET http://localhost:80/api/setColor/blue

### test acceleration
GET http://localhost:80/api/accelerations

### test get sensitivity
GET http://localhost:80/api/settings/sensitivity

### test post sensitivity
POST http://localhost:80/api/settings/sensitivity
Content-Type: application/json

{ "sensitivity" : "VERY_LOW" }

### test post sensitivity
POST http://localhost:80/api/settings/sortToddler/duration
Content-Type: application/json

{ "duration" : 31 }

### test post language
POST http://localhost:80/api/settings/language
Content-Type: application/json

{ "language" : "de" }

### test force start game
POST http://localhost:80/api/game/force-start
Content-Type: application/json

{
  "gameMode": "FreeForAll",
  "forceActivateAllController": true
}

### test force stop game
POST http://localhost:80/api/game/force-stop
Content-Type: application/json

{}

### play sound test
GET http://localhost:80/api/playsound/two

### get sound map
GET http://localhost:80/api/soundmap

### play all sounds as MP3
GET http://localhost:80/api/playAllSoundsAsMp3

### play all sounds as WAV
GET http://localhost:80/api/playAllSoundsAsWav


### test force stop game
DELETE http://joust.mania/api/clear-device/04:76:6e:b8:29:64