### play sound test
GET http://localhost:8080/api/playsoundtest

### start color animation for all controllers
GET http://localhost:8080/api/setColorAnimation

### test color animation without loop
GET http://localhost:8080/api/setRedAnimationTest

### test rumble
GET http://localhost:8080/api/rumble/255

### test set Color
GET http://localhost:8080/api/setColor/pastel_green

### test set Color
GET http://localhost:8080/api/setColor/light_blue

### test set Color
GET http://localhost:8080/api/setColor/aqua

### test set Color
GET http://localhost:8080/api/setColor/green

### test set Color
GET http://localhost:8080/api/setColor/blue

### test acceleration
GET http://localhost:8080/api/accelerations

### test get sensitivity
GET http://localhost:8080/api/settings/sensitivity

### test post sensitivity
POST http://localhost:8080/api/settings/sensitivity
Content-Type: application/json

{ "sensitivity" : "VERY_LOW" }