package de.vanfanel.joustmania.sound

import de.vanfanel.joustmania.sound.SoundId.*
import de.vanfanel.joustmania.sound.SupportedSoundLocale.EN
import de.vanfanel.joustmania.sound.SupportedSoundLocale.DE
import de.vanfanel.joustmania.types.MoveColor
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.nio.file.Paths
import kotlin.jvm.javaClass

/**
 * Sounds were generated by elevenlabs.
 * Settings:
 *
 * Voice: Will
 * Model: Eleven Multilingual v2
 * Speed: 0.91
 * Stability: 31%
 * Similarity: 19%
 * Style Exaggeration: 43%
 * Speaker Boost: yes
 */

@Serializable
enum class SupportedSoundLocale {
    EN, DE
}

@Serializable
data class Sound(
    val id: SoundId,
    val soundFiles: Map<SupportedSoundLocale, SoundFile>
)

@Serializable
data class SoundFile(
    val language: SupportedSoundLocale,
    val file: String,
    val localizedText: String,
) {
    fun getWavSoundPath(): String {
        return "/sound/${language.name.lowercase()}/wav/$file.wav"
    }

    @Suppress("unused")
    fun getMp3SoundPath(): String {
        return "/sound/${language.name.lowercase()}/mp3/$file.mp3"
    }
}

@Serializable
enum class SoundId {
    NEW_CONTROLLER,
    CONTROLLER_DISCONNECTED,
    ADMIN_GRANTED,
    ADMIN_REVOKED,
    CONTROLLER_JOINED,
    CONTROLLER_LEFT,
    GAME_MODE_FFA,
    GAME_MODE_TODDLERS,
    GAME_MODE_WEREWOLF,
    ALL_PLAYERS_READY,
    THREE,
    TWO,
    ONE,
    GO,
    GAME_MODE_FFA_EXPLANATION,
    GAME_MODE_TODDLER_EXPLANATION,
    GAME_MODE_WEREWOLF_EXPLANATION,
    GAME_MODE_WEREWOLF_EXPLANATION_TWO,
    AQUA_WINS,
    BLACK_WINS,
    BLUE_WINS,
    GREEN_WINS,
    LIGHT_BLUE_WINS,
    LIME_WINS,
    MAGENTA_WINS,
    ORANGE_WINS,
    PINK_WINS,
    RED_WINS,
    VIOLET_WINS,
    WHITE_WINS,
    YELLOW_WINS,
    PLAYER_LOSE_1,
    PLAYER_LOSE_2,
    MINIMUM_PLAYERS_2,
    MINIMUM_PLAYERS_3
    ;

    companion object {
        fun colorToSound(color: MoveColor?): SoundId? {
            return when(color) {
                MoveColor.AQUA -> AQUA_WINS
                MoveColor.BLACK -> BLACK_WINS
                MoveColor.BLUE -> BLUE_WINS
                MoveColor.GREEN -> GREEN_WINS
                MoveColor.LIGHT_BLUE -> LIGHT_BLUE_WINS
                MoveColor.LIME -> LIME_WINS
                MoveColor.MAGENTA -> MAGENTA_WINS
                MoveColor.ORANGE -> ORANGE_WINS
                MoveColor.PINK -> PINK_WINS
                MoveColor.RED -> RED_WINS
                MoveColor.VIOLET -> VIOLET_WINS
                MoveColor.WHITE -> WHITE_WINS
                MoveColor.YELLOW -> YELLOW_WINS
                else -> null
            }
        }

        fun fromString(string: String?): SoundId? {
            if (string == null) return null
            return try {
                valueOf(string.uppercase())
            } catch (_: IllegalArgumentException) {
                null
            }
        }
    }
}

val soundMap: Map<SoundId, Sound> by lazy {
    loadSoundMap()
}

fun loadSoundMap(): Map<SoundId, Sound> {
    // Define the path to the "sounds.json" file in the resources directory
    val inputStream = {}.javaClass.getResourceAsStream("/sound/sounds.json")
    if (inputStream == null) {
        throw IllegalStateException("Cannot find sounds.json in resources/sound")
    }
    val text = inputStream.bufferedReader().use { it.readText() }
    return Json.decodeFromString(text)
}

fun getSoundBy(id: SoundId, locale: SupportedSoundLocale): SoundFile? {
    return soundMap[id]?.soundFiles?.get(locale)
}