package de.vanfanel.joustmania.sound

import de.vanfanel.joustmania.sound.SoundId.*
import de.vanfanel.joustmania.sound.SupportedSoundLocale.EN
import de.vanfanel.joustmania.sound.SupportedSoundLocale.DE
import de.vanfanel.joustmania.types.MoveColor

/**
 * Sounds were generated by elevenlabs.
 * Settings:
 *
 * Voice: Will
 * Model: Eleven Multilingual v2
 * Speed: 0.91
 * Stability: 31%
 * Similarity: 19%
 * Style Exaggeration: 43%
 * Speaker Boost: yes
 */


enum class SupportedSoundLocale {
    EN, DE
}

data class Sound(
    val id: SoundId,
    val soundFiles: Map<SupportedSoundLocale, SoundFile>
)

data class SoundFile(
    val language: SupportedSoundLocale,
    val file: String,
    val localizedText: String,
) {
    fun getWavSoundPath(): String {
        return "/sound/${language.name.lowercase()}/wav/$file.wav"
    }

    @Suppress("unused")
    fun getMp3SoundPath(): String {
        return "/sound/${language.name.lowercase()}/mp3/$file.mp3"
    }
}

enum class SoundId {
    NEW_CONTROLLER,
    CONTROLLER_DISCONNECTED,
    ADMIN_GRANTED,
    ADMIN_REVOKED,
    CONTROLLER_JOINED,
    CONTROLLER_LEFT,
    GAME_MODE_FFA,
    GAME_MODE_TODDLERS,
    ALL_PLAYERS_READY,
    THREE,
    TWO,
    ONE,
    GO,
    GAME_MODE_FFA_EXPLANATION,
    GAME_MODE_TODDLER_EXPLANATION,
    AQUA_WINS,
    BLACK_WINS,
    BLUE_WINS,
    GREEN_WINS,
    LIGHT_BLUE_WINS,
    LIME_WINS,
    MAGENTA_WINS,
    ORANGE_WINS,
    PINK_WINS,
    RED_WINS,
    VIOLET_WINS,
    WHITE_WINS,
    YELLOW_WINS,
    PLAYER_LOSE_1,
    PLAYER_LOSE_2,
    MINIMUM_PLAYERS_2,
    MINIMUM_PLAYERS_3
    ;

    companion object {
        fun colorToSound(color: MoveColor?): SoundId? {
            return when(color) {
                MoveColor.AQUA -> AQUA_WINS
                MoveColor.BLACK -> BLACK_WINS
                MoveColor.BLUE -> BLUE_WINS
                MoveColor.GREEN -> GREEN_WINS
                MoveColor.LIGHT_BLUE -> LIGHT_BLUE_WINS
                MoveColor.LIME -> LIME_WINS
                MoveColor.MAGENTA -> MAGENTA_WINS
                MoveColor.ORANGE -> ORANGE_WINS
                MoveColor.PINK -> PINK_WINS
                MoveColor.RED -> RED_WINS
                MoveColor.VIOLET -> VIOLET_WINS
                MoveColor.WHITE -> WHITE_WINS
                MoveColor.YELLOW -> YELLOW_WINS
                else -> null
            }
        }

        fun fromString(string: String?): SoundId? {
            if (string == null) return null
            return try {
                valueOf(string.uppercase())
            } catch (_: IllegalArgumentException) {
                null
            }
        }
    }
}

private val soundMap: Map<SoundId, Sound> = mapOf(
    NEW_CONTROLLER to Sound(
        id = NEW_CONTROLLER, soundFiles = mapOf(
            EN to SoundFile(language = EN, file = "new_controller", localizedText = "New Controller connected")
        )
    ),
    CONTROLLER_DISCONNECTED to Sound(
        id = CONTROLLER_DISCONNECTED, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "controller_disconnected",
                localizedText = "Controller disconnected"
            )
        )
    ),
    ADMIN_GRANTED to Sound(
        id = ADMIN_GRANTED, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "admin_granted",
                localizedText = "TODO fill me"
            )
        )
    ),
    ADMIN_REVOKED to Sound(
        id = ADMIN_REVOKED, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "admin_revoked",
                localizedText = "TODO fill me"
            )
        )
    ),
    CONTROLLER_JOINED to Sound(
        id = CONTROLLER_JOINED, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "controller_joined",
                localizedText = "TODO fill me"
            )
        )
    ),
    CONTROLLER_LEFT to Sound(
        id = CONTROLLER_LEFT, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "controller_left",
                localizedText = "TODO fill me"
            )
        )
    ),
    GAME_MODE_FFA to Sound(
        id = GAME_MODE_FFA, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "game_mode_ffa",
                localizedText = "Game Mode: Free For All"
            )
        )
    ),
    GAME_MODE_TODDLERS to Sound(
        id = GAME_MODE_TODDLERS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "game_mode_toddlers",
                localizedText = "Game Mode: Sort Toddlers"
            )
        )
    ),
    ALL_PLAYERS_READY to Sound(
        id = ALL_PLAYERS_READY, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "all_players_ready",
                localizedText = "All players are ready."
            )
        )
    ),
    THREE to Sound(
        id = THREE, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "three",
                localizedText = "3"
            )
        )
    ),
    TWO to Sound(
        id = TWO, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "two",
                localizedText = "two"
            )
        )
    ),
    ONE to Sound(
        id = TWO, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "one",
                localizedText = "1"
            )
        )
    ),
    GO to Sound(
        id = GO, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "go",
                localizedText = "GO!"
            )
        )
    ),
    GAME_MODE_FFA_EXPLANATION to Sound(
        id = GAME_MODE_FFA_EXPLANATION, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "game_mode_ffa_explanation",
                localizedText = """A new round of "Free for all" is started. Protect your controller and try to accelerate your opponents' controllers at the same time. If you accelerate too quickly, you are out. The last player wins. Everyone ready? The game starts in:"""
            ),
            DE to SoundFile(
                language = DE,
                file = "game_mode_ffa_explanation",
                localizedText = """Eine neue Runde "Jeder gegen Jeden" wird gestartet. Beschütze deinen Controller und versuche gleichzeitig die Controller deiner Gegner zu Beschleunigen. Beschleunigst du zu schnell bist du raus. Der letzte Spieler gewinnt. Alle Bereit? Das spiel startet in:"""
            )
        )
    ),
    GAME_MODE_TODDLER_EXPLANATION to Sound(
        id = GAME_MODE_TODDLER_EXPLANATION, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "game_mode_toddler_explanation",
                localizedText = """We start a round of color sorting game: Just sort yourselves by color! Here we go"""
            ),
            DE to SoundFile(
                language = DE,
                file = "game_mode_toddler_explanation",
                localizedText = """Wir starten eine Runde Farbkasten-Spiel: Sortiert euch einfach nach Farben! Los gehts"""
            )
        )
    ),
    AQUA_WINS to Sound(
        id = AQUA_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "aqua_wins",
                localizedText = """player "aqua" wins!"""
            )
        )
    ),
    BLACK_WINS to Sound(
        id = BLACK_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "black_wins",
                localizedText = """player "black" wins!"""
            )
        )
    ),
    BLUE_WINS to Sound(
        id = BLACK_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "blue_wins",
                localizedText = """player "blue" wins!"""
            )
        )
    ),
    GREEN_WINS to Sound(
        id = GREEN_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "green_wins",
                localizedText = """player "green" wins!"""
            )
        )
    ),
    LIGHT_BLUE_WINS to Sound(
        id = LIGHT_BLUE_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "light_blue_wins",
                localizedText = """player "light blue" wins!"""
            )
        )
    ),
    LIME_WINS to Sound(
        id = LIME_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "lime_wins",
                localizedText = """player "lime" wins!"""
            )
        )
    ),
    MAGENTA_WINS to Sound(
        id = MAGENTA_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "magenta_wins",
                localizedText = """player "magenta" wins!"""
            )
        )
    ),
    ORANGE_WINS to Sound(
        id = ORANGE_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "orange_wins",
                localizedText = """player "orange" wins!"""
            )
        )
    ),
    PINK_WINS to Sound(
        id = PINK_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "pink_wins",
                localizedText = """player "pink" wins!"""
            )
        )
    ),
    RED_WINS to Sound(
        id = RED_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "red_wins",
                localizedText = """player "red" wins!"""
            )
        )
    ),
    VIOLET_WINS to Sound(
        id = VIOLET_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "violet_wins",
                localizedText = """player "violet" wins!"""
            )
        )
    ),
    WHITE_WINS to Sound(
        id = WHITE_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "white_wins",
                localizedText = """player "white" wins!"""
            )
        )
    ),
    YELLOW_WINS to Sound(
        id = YELLOW_WINS, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "yellow_wins",
                localizedText = """player "yellow" wins!"""
            )
        )
    ),
    PLAYER_LOSE_1 to Sound(
        id = PLAYER_LOSE_1, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "player_lose_1",
                localizedText = ""
            )
        )
    ),
    PLAYER_LOSE_2 to Sound(
        id = PLAYER_LOSE_2, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "player_lose_2",
                localizedText = ""
            )
        )
    ),
    MINIMUM_PLAYERS_2 to Sound(
        id = MINIMUM_PLAYERS_2, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "minimum_players_2",
                localizedText = "To play this game, you need at least 2 players"
            ),
        )
    ),
    MINIMUM_PLAYERS_3 to Sound(
        id = MINIMUM_PLAYERS_3, soundFiles = mapOf(
            EN to SoundFile(
                language = EN,
                file = "minimum_players_3",
                localizedText = "To play this game, you need at least 3 players"
            ),
        )
    )
)

fun getSoundBy(id: SoundId, locale: SupportedSoundLocale): SoundFile? {
    return soundMap[id]?.soundFiles?.get(locale)
}