/**
 * Sounds were generated by elevenlabs.
 * Settings:
 *
 * Voice:  Will
 * Model: Eleven Multilingual v2
 * Speed: 0.91
 * Stability: 31%
 * Similarity: 19%
 * Style Exaggeration: 43%
 * Speaker Boost: yes
 */


typealias SoundId = String

data class Sound(
    val id: SoundId,
    val textEn: String,
    val soundFile: String,
)

val soundMap: Map<SoundId, Sound> = mapOf(
    "NEW_CONTROLLER" to Sound(id = "NEW_CONTROLLER", textEn = "New Controller connected", soundFile = ""),
    "CONTROLLER_DISCONNECTED" to Sound(id = "CONTROLLER_DISCONNECTED", textEn = "Controller disconnected", soundFile = "")
)